parameters:

  # ...
  update.manifest.location: "http://mycompany.com/{name}/manifest.json"

  # commands
  common.commands.update.class:  Ftven\Build\Cli\Extension\Core\Command\UpdateCommand
  common.commands.package.class: Ftven\Build\Cli\Extension\Core\Command\PackageCommand

  # services
  symfony.filesystem.filesystem.class: Symfony\Component\Filesystem\Filesystem
  symfony.yaml.yaml.class:             Symfony\Component\Yaml\Yaml
  symfony.yaml.dumper.class:           Symfony\Component\Yaml\Dumper
  symfony.yaml.parser.class:           Symfony\Component\Yaml\Parser
  twig.environment.class:              Twig_Environment
  twig.loaders.filesystem.class:       Twig_Loader_Filesystem
  guzzlehttp.client.class :            GuzzleHttp\Client
  common.services.updateManager.class: Herrera\Phar\Update\Manager

  common.services.filesystem.class:    Ftven\Build\Common\Service\Filesystem\FilesystemService
  common.services.box.class:           Ftven\Build\Common\Service\Box\BoxService
  common.services.system.class:        Ftven\Build\Common\Service\System\SystemService
  common.services.phpunit.class:       Ftven\Build\Common\Service\Phpunit\PhpunitService
  common.services.git.class:           Ftven\Build\Common\Service\Git\GitService
  common.services.yaml.class:          Ftven\Build\Common\Service\Yaml\YamlService
  common.services.json.class:          Ftven\Build\Common\Service\Json\JsonService
  common.services.templating.class:    Ftven\Build\Common\Service\Templating\TemplatingService
  common.services.email.class:         Ftven\Build\Common\Service\Email\EmailService
  common.services.http.class:          Ftven\Build\Common\Service\Http\HttpService


services:

  # commands
  common.commands.update:
    class: %common.commands.update.class%
    arguments:
      - %update.manifest.location%
    tags:
      - {name: cli.command}
  common.commands.package:
    class: %common.commands.package.class%
    tags:
      - {name: cli.command}
    calls:
      - [setBoxService, [@common.services.box]]

  twig.environment:
    class: %twig.environment.class%
    arguments:
      - @twig.loaders.filesystem
  twig.loaders.filesystem:
    class: %twig.loaders.filesystem.class%
  symfony.filesystem.filesystem:
    class: %symfony.filesystem.filesystem.class%
  symfony.yaml.yaml:
    class: %symfony.yaml.yaml.class%
  symfony.yaml.dumper:
    class: %symfony.yaml.dumper.class%
  symfony.yaml.parser:
    class: %symfony.yaml.parser.class%
  guzzlehttp.client:
    class: %guzzlehttp.client.class%
  common.services.filesystem:
    class: %common.services.filesystem.class%
    calls:
      - [setFilesystem, [@symfony.filesystem.filesystem]]
  common.services.system:
    class: %common.services.system.class%
  common.services.box:
    class: %common.services.box.class%
    calls:
      - [setSystemService,     [@common.services.system]]
      - [setPhpunitService,    [@common.services.phpunit]]
      - [setFilesystemService, [@common.services.filesystem]]
      - [setJsonService,       [@common.services.json]]
  common.services.yaml:
    class: %common.services.yaml.class%
    calls:
      - [setFilesystemService, [@common.services.filesystem]]
      - [setYamlDumper, [@symfony.yaml.dumper]]
      - [setYamlParser, [@symfony.yaml.parser]]
  common.services.phpunit:
    class: %common.services.phpunit.class%
    calls:
      - [setSystemService, [@common.services.system]]
  common.services.json:
    class: %common.services.json.class%
    calls:
      - [setFilesystemService, [@common.services.filesystem]]
  common.services.git:
    class: %common.services.git.class%
    calls:
      - [setSystemService, [@common.services.system]]
  common.services.templating:
    class: %common.services.templating.class%
    calls:
      - [setTwig, [@twig.environment]]
  common.services.email:
    class: %common.services.email.class%
  common.services.http:
    class: %common.services.http.class%
    calls:
      - [setGuzzleClient, [@guzzlehttp.client]]

